spring:
  application:
    name: spring-boot-kotlin-crud-with-ci-cd
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=require&user=${DB_USER}&password=${DB_PASSWORD}
    hikari:
      auto-commit: true
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
