spring:
  application:
    name: spring-boot-kotlin-crud-with-ci-cd
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    hikari:
      auto-commit: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
